#pragma once

#include <stdint.h>

#define STATE_SEND_MASK 0xff00
#define STATE_RECEIVE_MASK 0x00ff
#define STATE_SEND_RECEIVE_MASK STATE_SEND_MASK | STATE_RECEIVE_MASK

typedef enum : uint16_t
{
  STATE_UNSPEC = 0,

  STATE_PACKET_COUNT = 0x0101,
  STATE_PACKETS = 0x0202,
  STATE_LOST_PACKET_NUMS = 0x0404,

  STATE_RECEIVE_PACKET_COUNT = (STATE_RECEIVE_MASK & STATE_PACKET_COUNT),
  STATE_RECEIVE_PACKETS = (STATE_RECEIVE_MASK & STATE_PACKETS),
  STATE_RECEIVE_LOST_PACKET_NUMS
  = (STATE_RECEIVE_MASK & STATE_LOST_PACKET_NUMS),

  STATE_SEND_PACKET_COUNT = (STATE_SEND_MASK & STATE_PACKET_COUNT),
  STATE_SEND_PACKETS = (STATE_SEND_MASK & STATE_PACKETS),
  STATE_SEND_LOST_PACKET_NUMS = (STATE_SEND_MASK & STATE_LOST_PACKET_NUMS),

  STATE_COMPLETE = 0x8080,
} packet_state_t;

typedef uint32_t packet_num_t;
typedef uint16_t packet_size_t;
