#pragma once

#include <stdint.h>

#define STATE_SEND_MASK 0xffff0000
#define STATE_RECEIVE_MASK 0x0000ffff
#define STATE_SEND_RECEIVE_MASK STATE_SEND_MASK | STATE_RECEIVE_MASK

typedef enum
{
  STATE_UNSPEC = 0,

  STATE_PACKET_COUNT = 0x00010001,
  STATE_TIMEOUT = 0x00020002,
  STATE_PACKETS = 0x00040004,
  STATE_LOST_PACKET_NUMS = 0x00080008,

  STATE_RECEIVE_PACKET_COUNT = (STATE_RECEIVE_MASK & STATE_PACKET_COUNT),
  STATE_RECEIVE_TIMEOUT = (STATE_RECEIVE_MASK & STATE_TIMEOUT),
  STATE_RECEIVE_PACKETS = (STATE_RECEIVE_MASK & STATE_PACKETS),
  STATE_RECEIVE_LOST_PACKET_NUMS
  = (STATE_RECEIVE_MASK & STATE_LOST_PACKET_NUMS),

  STATE_SEND_PACKET_COUNT = (STATE_SEND_MASK & STATE_PACKET_COUNT),
  STATE_SEND_TIMEOUT = (STATE_SEND_MASK & STATE_TIMEOUT),
  STATE_SEND_PACKETS = (STATE_SEND_MASK & STATE_PACKETS),
  STATE_SEND_LOST_PACKET_NUMS = (STATE_SEND_MASK & STATE_LOST_PACKET_NUMS),

  STATE_COMPLETE = 0x40004000,
} packet_state_t;

typedef uint32_t packet_num_t;
typedef uint16_t packet_size_t;
